const GameActionTypes = {
   ADD_PLAYER_TO_5: 'ADD_PLAYER_TO_5',
   SET_BENCH: 'SET_BENCH',
   TOGGLE_TIME_RUNNING: 'TOGGLE_TIME_RUNNING',
   TOGGLE_POSSESSION: 'TOGGLE_POSSESSION',
   SET_TIME: 'SET_TIME',
   SUB_PLAYERS: 'SUB_PLAYERS',
   SELECT_PLAYER: 'SELECT_PLAYER',
   ADD_BLOCK: 'ADD_BLOCK',
   ADD_STEAL: 'ADD_STEAL',
   ADD_DREB: 'ADD_DREB',
   ADD_DFOUL: 'ADD_DFOUL',
   ADD_OREB: 'ADD_OREB',
   ADD_OFOUL: 'ADD_OFOUL',
   ADD_TOV: 'ADD_TOV',
   OPPONENT_SCORE: 'OPPONENT_SCORE',
   SHOT: 'SHOT',
   SET_OPPONENT_NAME: 'SET_OPPONENT_NAME',
   RESET_GAME: 'RESET_GAME'
}

export default GameActionTypes