const TeamActionTypes = {
   ADD_PLAYER: 'ADD_PLAYER',
   REMOVE_PLAYER: 'REMOVE_PLAYER',
   FETCH_TEAM_START: 'FETCH_TEAM_START',
   FETCH_TEAM_SUCCESS: 'FETCH_TEAM_SUCCESS',
   FETCH_TEAM_FAIL: 'FETCH_TEAM_FAIL',
   RESET_TEAM: 'RESET_TEAM'
}

export default TeamActionTypes